server:
  port: 8084
  
spring:
  application:
    name: API_GATEWAY
    
  cloud:
    gateway:
      routes:
      - id: userservice
        uri:
          lb://userservice
        predicates:
        - Path=/api/v1/userservice/**
        
        
      - id: recommendations
        uri:
          lb://recommendations
        predicates:
        - Path=/api/v1/player/**
        
        
      - id: favoriteservice
        uri:
          lb://favoriteservice
        predicates:
        - Path=/api/v1/favoriteservice/**
        
        
        
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8767/eureka/
    fetch-registry: true
    register-with-eureka: true
    
  

    
    
    